from .templates import (  # noqa: F401
    STEP1_SYSTEM,
    STEP2_SYSTEM,
    STEP3_SYSTEM,
    STEP4_SYSTEM,
    STEP5_SYSTEM,
    STEP6_SYSTEM,
    STEP7_SYSTEM,
    STEP8_SYSTEM,
    STEP9_SYSTEM,
    SUFFICIENCY_SCORING_SYSTEM,
    WEAK_JUDGMENT_SYSTEM,
)
